title: Glamorous Toolkit

author: feenk gmbh

tagline: Glamorous Toolkit is the moldable development environment.
description:  Glamorous Toolkit empowers you to make systems explainable through experiences tailored for each problem.
url: https://gtoolkit.com/

twitter:
  username: feenkcom
  card: summary

logo: /assets/pictures/gtoolkit-icon.png

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag